name: Create Bucket
run-name: ${{ github.actor }} is destroying GCP Bucket
on: [push]
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v3

      # setup node (typescript)
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: "install dependencies"
        run: npm install

      # Google Github Actions
      - name: "auth GCP"
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_TOKEN }}"

      - name: "setup GCP"
        uses: "google-github-actions/setup-gcloud@v1"

      # Pulumi github actions
      - name: "exec pulumi"
        uses: pulumi/actions@v4
        with:
          # command: preview
          # command: up
          command: destroy
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}

# pulumi preview: allows you to see what changes will be made before actually applying them. This is useful for reviewing the changes and ensuring that they are as expected.
# pulumi up: applies the changes to your infrastructure. It will create, update, or delete resources as necessary to match the desired state defined in your Pulumi program.
# pulumi destroy: removes all resources managed by the Pulumi stack. This is useful for cleaning up resources when they are no longer needed.
